### ISSUE TITLE
Ramping polygon-pattern-file property

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/turbo-carto#57]
### Details

* Feature request made by a user from SB.
* It should be great to be able to ramp `polygon-pattern-file` property.

### Feature request

* A query such as this one should work:

```css
#layer{	
  polygon-pattern-file: ramp([continent], (url(https://s3.amazonaws.com/com.cartodb.users-assets.production/production/stephaniemongon/assets/20150607041630diag-w.png), url(https://s3.amazonaws.com/com.cartodb.users-assets.production/production/mamatablog/assets/20151025140245land_paper.png)), category(2));
  polygon-pattern-opacity: 0.4;
  polygon-fill: #c3d1c7;
}
```
