### ISSUE TITLE
Using variables within ramp functions do not work

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/turbo-carto#58]
* Using CartoCSS variables instead of colors or numbers do not work.
* Implementing this in BUILDER should be great as well. 

```css
\* Metro Lines Colors *\
@l1: #01bff5;
@l10: #014ea5;
@l11: #01836b;
@l12: #849a01;
@l2: #fe1225;
@l3: #fed201; 
@l4: #a75608; 
@l5: #34c83a; 
@l6: #949492; 
@l7: #fe862d; 
@l8: #fe82b0; 
@l9: #b91a8d; 
@ml1: #014ea5;
@ml2: #b91a8d;
@ml3: #fe1225;
@lr: #000000;

\* Metro Lines Style *\
#layer {
  line-width: 1;
  line-color: ramp([name], (@l1, @l2, @l3 ... @lr), category(16));
}
```
cc @makella @piensaenpixel
